### ISSUE TITLE
Azure Sentinel + Custom Log Pipeline ARM Template fails with copy variable error

### ISSUE THREAD

**Issue by AndyHerb** [OTRF/Azure-Sentinel2Go#1]
Hi - I tried to deploy the Sentinel 2 Go lab using the Custom Log Pipeline option and it appears that the nested [Linux VM deployment script](https://github.com/OTRF/Blacksmith/blob/master/templates/azure/Linux/azuredeploy.json) is failing due to the count values in the _centOSVMs_ and _redhatVMs_ Copy variables both being zero.  The error I received was:

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Deployment template validation failed: 'The template 'copy' definition at line '283' and column '17' has an invalid copy count. The copy count must be a positive integer value and cannot exceed '800'. Please see https://aka.ms/arm-copy for usage details.'.\",\r\n \"additionalInfo\": [\r\n {\r\n \"type\": \"TemplateViolation\",\r\n \"info\": {\r\n \"lineNumber\": 283,\r\n \"linePosition\": 17,\r\n \"path\": \"variables.Copy\"\r\n }\r\n }\r\n ]\r\n }\r\n}"}]}`

The input parameters (obfuscated where relevant) were:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "workspaceName": {
            "value": "xxxxxxxxxxxxxx"
        },
        "pricingTier": {
            "value": "Free"
        },
        "dataRetention": {
            "value": 7
        },
        "immediatePurgeDataOn30Days": {
            "value": true
        },
        "adminUsername": {
            "value": "SecureUsername"
        },
        "authenticationType": {
            "value": "password"
        },
        "adminPasswordOrKey": {
            "value": "SecurePassword"
        },
        "vmSize": {
            "value": "Standard_B2s"
        },
        "allowedIPAddresses": {
            "value": "My.Home.IP.Address"
        },
        "addMordorDatasets": {
            "value": "mordor-large-apt29(2.0GB)"
        },
        "deployCustomLogsPipeline": {
            "value": "Logstash-EventHub"
        },
        "location": {
            "value": "uksouth"
        }
    }
}
```

Regards,
  Andy

**Comment by Cyb3rWard0g** [comment]
Hey @AndyHerb ! Thank you for the heads up. I remember seeing that error but when I updated the schema version for the deployment, it went away. Let me give it a try .

**Comment by Cyb3rWard0g** [comment]
I tried to deploy the `Azure Sentinel + Linux VM(Ubuntu, Centos, RedHat)` template, and it works fine. 

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/9653181/91620904-4a8ad980-e95f-11ea-9783-9ca348eb372f.png">

I will now test the `custom-log pipeline`

**Comment by Cyb3rWard0g** [comment]
mmmm I see the schema for that template is `2019-05-01`

https://github.com/OTRF/Azure-Sentinel2Go/blob/master/grocery-list/custom-log-pipeline/azuredeploy.json#L156

I will update it to `2020-06-01`

https://github.com/OTRF/Azure-Sentinel2Go/blob/master/grocery-list/linux/azuredeploy.json#L258

**Comment by AndyHerb** [comment]
Many thanks for the quick turnaround - that's solved the first problem, unfortunately it looks like I've hit another issue which need a small tweak:

The output from the [Linux VM script](https://github.com/OTRF/Blacksmith/blob/master/templates/azure/Linux/azuredeploy.json) is currently in the form of an Array called **allLinuxVMsDeployed** [https://github.com/OTRF/Blacksmith/blob/master/templates/azure/Linux/azuredeploy.json#L558](https://github.com/OTRF/Blacksmith/blob/master/templates/azure/Linux/azuredeploy.json#L558) whereas the **CustomLogsPipeline** resource is looking to send a property value for vmName to _linkedtemplates/customScript.json_ from `[reference('deployLogstashVM').outputs.vmName.value]`

**Comment by Cyb3rWard0g** [comment]
ok I made some changes to it and I chose

Custom Logs PIpeline
* LinuxVM (logstash)
* Mordor Dataset 1GB

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/9653181/91621820-7cea0600-e962-11ea-9147-a5e595bfddd5.png">

it seems that it like the changes so far. but I believe I need to update a few things in Logstash. There are some recent changes that it doesnt ike anymore

**Comment by Cyb3rWard0g** [comment]
> Many thanks for the quick turnaround - that's solved the first problem, unfortunately it looks like I've hit another issue which need a small tweak:
> 
> The output from the [Linux VM script](https://github.com/OTRF/Blacksmith/blob/master/templates/azure/Linux/azuredeploy.json) is currently in the form of an Array called **allLinuxVMsDeployed** https://github.com/OTRF/Blacksmith/blob/master/templates/azure/Linux/azuredeploy.json#L558 whereas the **CustomLogsPipeline** resource is looking to send a property value for vmName to _linkedtemplates/customScript.json_ from `[reference('deployLogstashVM').outputs.vmName.value]`

Yes I fixed that too. In the LinuxVM template used to deploy logstash, now it outputs an ARRAY and not just one variable. I fixed that but I believe the installation of logstash is taking longer than expected. I will work on it tonight.

**Comment by Cyb3rWard0g** [comment]
Ok I just tested :

Small datasets + Logstash + Azure Sentinel and it works 👍 

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/9653181/91629025-2943e080-e993-11ea-9922-26faa46b174f.png">

I assume the EventHub works too since it is a service added to the Azure Sentinel + Logstash setup. Can you please confirm if your use case works? Thank you @AndyHerb

**Comment by Cyb3rWard0g** [comment]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/9653181/91629077-a1aaa180-e993-11ea-916e-1810337b01fb.png">

it works ;) 

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/9653181/91629132-33b2aa00-e994-11ea-8950-b4708844d106.png">

**Comment by Cyb3rWard0g** [comment]
https://github.com/OTRF/Azure-Sentinel2Go/commit/847ae7b1cc9c064f669200793ccd7c0f2c6b5cd2 (Schema Version update)
https://github.com/OTRF/Azure-Sentinel2Go/commit/3e0b30ce68e2d19f82593a47e04235f81363a72c
https://github.com/OTRF/Azure-Sentinel2Go/commit/b928d203fd8d53a75e74f33c0654cb61820f865f

**Comment by AndyHerb** [comment]
@Cyb3rWard0g - that's fantastic, thanks 👍 

I can confirm that it's also worked a treat for me too - currently ingesting the 2GB Mordor data set.

![SentinelScreenshot](https://user-images.githubusercontent.com/12876870/91646542-16d7ae80-ea48-11ea-8a33-177bd902598c.png)

Many thanks again for your assistance and prompt turnaround on these issues.  Looking forward to Part 2 of the blog.

**Comment by Cyb3rWard0g** [comment]
That's awesome! Thank you for checking the other options. happy to see all that data being available for you ;) . Yes I am in the process of integrating Azure-Sentinel2Go with other platforms and write about it :) that's part 2
