### ISSUE TITLE
Missing json

### ISSUE THREAD

**Issue by acidflash** [OTRF/Azure-Sentinel2Go#10]
I got 404 when i try to deploy any of this
https://raw.githubusercontent.com/OTRF/Azure-Sentinel2Go/master/grocery-list/Win10/azuredeploy.json
https://raw.githubusercontent.com/OTRF/Azure-Sentinel2Go/master/grocery-list/Win10-AD/azuredeploy.json
https://raw.githubusercontent.com/OTRF/Azure-Sentinel2Go/master/grocery-list/Win10-AD-ADFS/azuredeploy.json
https://raw.githubusercontent.com/OTRF/Azure-Sentinel2Go/master/grocery-list/Win10-PAN-FW/azuredeploy.json
https://raw.githubusercontent.com/OTRF/Azure-Sentinel2Go/master/grocery-list/Linux/azuredeploy.json

I used https://raw.githubusercontent.com/OTRF/Azure-Sentinel2Go/master/grocery-list/Win10-AD/azuredeploy.json for some days ago but now 404.

**Comment by Cyb3rWard0g** [comment]
Hello @acidflash ! Sorry for the inconvenience. I renamed the folders and I forgot that renaming folder locally does not get updated in the remote repo :( . I am about to push a fix for all that

**Comment by Cyb3rWard0g** [comment]
That should work now. Would you mind giving it a try? Thank you for letting me know @acidflash !

**Comment by acidflash** [comment]
Everything works just fine now. 
Thank you for fast fix.
