### ISSUE TITLE
Research Licence

### ISSUE THREAD

**Issue by SkiddyBargins** [OTRF/Azure-Sentinel2Go#11]
Really keen to get this set up for a more persistent research environment as a side project.

Have you come across any ways to get this up an running for non-academic researchers without having to commit to an Microsoft E5 license ?

**Comment by Cyb3rWard0g** [comment]
Hello @SkiddyBargins !  This does not require an E5 license unless you want to use Microsoft 365 defender security products such as Microsoft defender for endpoint, identity or cloud application security.
