### ISSUE TITLE
not a zip file

### ISSUE THREAD

**Issue by yayoayala** [OTRF/Azure-Sentinel2Go#12]
The below file is corrupted
 - dataset-sample-small.tar.gz

root@Kali:~/scrip$ tar -xzvf dataset-sample-small.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by Cyb3rWard0g** [comment]
Hello @yayoayala , I tested it in my WIndows box with 

```
tar -xvzf C:\PATH\TO\FILE\FILE-NAME.tar.gz
``

and it worked fine.
