### ISSUE TITLE
'The template variable 'ouPath' is not valid:

### ISSUE THREAD

**Issue by hfakar** [OTRF/Azure-Sentinel2Go#3]
Greetings Roberto..

Love your work! But currently having some trouble on deploying the Azure Sentinel + Win10 + Domain Controller Template.

Getting error on deployment phase deployWinAD fails:

`Deployment template validation failed: 'The template variable 'ouPath' is not valid: The language expression property array index '1' is out of bounds.. Please see https://aka.ms/arm-template-expressions for usage details.'. 
`

**Comment by Cyb3rWard0g** [comment]
Hey @hfakar ! sorry for the late response. Let me take a look at it.

**Comment by hfakar** [comment]
No worries! Will be waiting for your reply 👌

**Comment by Cyb3rWard0g** [comment]
Hey @hfakar , I have not forgotten about this issue. I was updating a few templates and restructuring a few items in the project. I will test this scenario this weekend. Than you for your patience.

**Comment by Cyb3rWard0g** [comment]
Hey @hfakar , I just tested it and worked as expected

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/9653181/95005801-83efde00-05ca-11eb-902d-4a5b45df0f59.png">

one thing I added by default to the template is the domain FQDN. it expects a specific format. Would you mind sharing what you provided as input for it? That parameters i used in the `ouPath` variable.

https://github.com/OTRF/Azure-Sentinel2Go/blob/master/grocery-list/win10-DC/azuredeploy.json#L142-L148

This is how the `ouPath` is used

https://github.com/OTRF/Blacksmith/blob/master/templates/azure/Win10-DC/azuredeploy.json#L314-L315

**Comment by Cyb3rWard0g** [comment]
I also forgot to say that I appreciate the feedback and support :) also thank you for your patience.

**Comment by hfakar** [comment]
The specific format expectation was the thing that broke the entire deployment. Thanks for pointing me in the right direction. 

Now I have a ready sentinel deployment. Oh also sorry for the late response. Its been crazy lately.
