### ISSUE TITLE
Deprecated configuration - logstash injestion module

### ISSUE THREAD

**Issue by le0li9ht** [OTRF/Azure-Sentinel2Go#4]
Hi,

As checked the old module for injesting logs via logstash to azure log analytics is giving a lot of errors.

Solution:
The new module(microsoft-logstash-output-azure-loganalytics 1.0.0 version) installation:
`/usr/share/logstash/bin/logstash-plugin install microsoft-logstash-output-azure-loganalytics 
`

loganalytics-output.conf
```
output {
   microsoft-logstash-output-azure-loganalytics {
      workspace_id => "<workspace-ID"
      workspace_key => "sharedkey"
      custom_log_table_name => "prerecorded"
      plugin_flush_interval => 5
   }
   #stdout { codec => rubydebug }
}
```

**Comment by Cyb3rWard0g** [comment]
Hey @le0li9ht , is the old one giving you errors through the templates in this project? I was waiting for the Microsoft one to be ready and it seems it is now? Niceee!!! I Ill do some testing and update it

**Comment by Cyb3rWard0g** [comment]
Works very well! :) Thank you @le0li9ht 

<img width="997" alt="image" src="https://user-images.githubusercontent.com/9653181/95156552-d402a800-0764-11eb-96ed-51cac01808b5.png">
